version: '3'

services:

  ### PHP ###################################################
  php:
    build:
      context: ./php
    container_name: siriusorm_php
    volumes:
      - ../:/var/www:delegated
    #ports:
    #  - "9000:9000"
    networks:
      - local

  sqlserver:
    image: microsoft/mssql-server-linux
    container_name: siriusorm_mssql
    ports:
      - "11433:1433"
    environment:
      SA_PASSWORD: "SSpaSS__1"
      ACCEPT_EULA: "Y"
    networks:
      - local

  mysql_latest:
    image: mysql:latest
    container_name: siriusorm_mysql
    restart: 'always'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: "siriusorm"
      MYSQL_ROOT_PASSWORD: "sirius"
      MYSQL_ROOT_HOST: "%"
    networks:
      - local

  postgres:
    image: postgres:12
    container_name: siriusorm_postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: "siriusorm"
      POSTGRES_USER: "sirius"
      POSTGRES_PASSWORD: "sirius"
    networks:
      - local

#Docker Networks
networks:
  local:
    driver: bridge
