name: CI

on:
  push:
    branches: [ dev_2x ]
  pull_request:
    branches: [ dev_2x ]

jobs:
  test:
    strategy:
      matrix:
        php: ['7.4']
#        include:
#            - php: '8.0'
#              composer-flags: '--ignore-platform-req=php'
#              phpunit-flags: '--no-coverage'

    runs-on: ubuntu-latest

#    services:
#      siriusorm_mysql:
#        image: mysql:5.7
#        env:
#          MYSQL_USER: sirius
#          MYSQL_PASSWORD: sirius
#          MYSQL_DATABASE: siriusorm
#          MYSQL_ROOT_PASSWORD: sirius
#        ports:
#          - 3306:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

#     - uses: mirromutth/mysql-action@v1.1
#       with:
#         mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
#         mysql database: 'siriusorm' # Optional, default value is "test". The specified database which will be create
#         mysql root password: 'rootpass' # Required if "mysql user" is empty, default is empty. The root superuser password
    - name: Setup DB services
      run: |
        cd tests
        docker-compose up -d
        cd ..

    - name: Verify MySQL connection
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P13306 --silent; do
          sleep 1
        done

    - name: Setup PHP with fail-fast
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: pcov
        tools: pecl
        extensions: mbstring, pdo, pdo_pgsql
      env:
        fail-fast: true

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      env:
        MYSQL_CONNECTION: 'mysql:host=127.0.0.1;port=13306;dbname=siriusorm'
        MYSQL_USER: 'root'
        MYSQL_PASS: 'sirius'
        POSTGRES_CONNECTION: 'pgsql:host=127.0.0.1;port=15432;dbname=siriusorm'
      run: |
        mkdir -p build/logs
        vendor/bin/phpunit

    - name: Upload to Scrutinizer-CI
      run: wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
